// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:18a4462c-c2ee-415b-beb6-c5339f8f07c0",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_mqPF4befk",
    "aws_user_pools_web_client_id": "1vppr8lcstcf2m6t4sig60k0kj",
    "aws_user_files_s3_bucket": "s3test590e3389334b4b2a93536416dc02d388-test",
    "aws_user_files_s3_bucket_region": "eu-west-1"
};


export default awsmobile;
